// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAndParseOpenAPI(arg1) {
  return window['go']['main']['App']['LoadAndParseOpenAPI'](arg1);
}

export function SelectOpenFile() {
  return window['go']['main']['App']['SelectOpenFile']();
}
